from typing import Protocol


class EventStore(Protocol):
    async def try_start(self, *, event_id: str, message_id: str | None) -> bool: ...

    async def mark_completed(self, event_id: str) -> None: ...

    async def mark_failed(self, event_id: str, error_code: str) -> None: ...
